README.md

Loopring Protocol v3 uses ZKP to scale DEX up to 525 trades(settlements) per second with a 1cent settlement fee per trade. Details are here: https://github.com/Loopring/protocols/blob/master/packages/loopring_v3/DESIGN.md#results

Add Loopring v3 as an example of using ZKP

---

README.md

zkPoD is a practical data exchange system based on the Ethereum applying ZKPs to ensure trading fairness. The system can support delivering large data file up to many GBs, and the computation complexity is quite efficient for participants with ordinary PCs.
Check technical papers for more details.
https://sec-bit.github.io/zkPoD-node/paper.pdf

Add zkPoD in ethereum ZKP application section

---

README.md

1. ressources -> resources
2. develpment -> development

docs: Spelling Correction

---

README.md

Added a link with a tutorial on how to use ZoKrates in Remix, could be useful for newcomers to space.

Updating tutorial for ZoKrates

---

README.md

https://twitter.com/gakonst/status/1217817046186151936?s=20
>ultra clearly articulated 3 hour deep-dive on Polynomial Commitments, worth your time if interested in understanding one of the core components behind Zero Knowledge Proofs
by @gakonst

added ZkStudyClub videos about Polynomial Commitments

---

README.md

Adding paper about SuperSonic.

SuperSonic paper added

---

README.md

The simplest possible SNARK for NP. 
This focuses on SSP instead of R1CS and is not zero-knowledge. But serves a very good starting point in understanding the basics of SNARKS and comes along with writeup and follow-along code.

Request to Add BabySNARK

---

README.md

The uiuc course on applied cryptography include many support document to understand zero knowledge proof and its potential applications.

pull request to add uiuc crypto course

---

README.md

Dark Forest is a real-time strategy game based upon zkSNARKs and Ethereum. I included a link to the website in the `Applications` section as well as their introductory blog post series in the `General introduction` section.

Add DarkForest resources

---

README.md

(This is the talk that the excellent already-existing slides link is associated with.)

Add youtube link to talk: Demystifying zk-proofs

---

README.md

Hi,
I have added the link to a very exhausting and detailed paper about Martin. 
Additionally, I have added the link to the zkproof.org website, where an active community of zk-people can be found and a lot of interesting resources are available.
Best

Marlin paper and zkproof.org links added to the README

---

README.md

"Strong" is not a cryptographic assumption

clarify cryptographic assumptions

---

README.md

Hi!
I propose a cheatsheet I have written from my notes about ZKPs, stemming from an ongoing Monero documentation effort (anyway this cheatsheet is agnostic, dealing only with theory, without any reference to actual projects)
I have tried to not miss the basic core concepts despite the simplified approach and topics selection, stressing ideas more than formalism: the merit of this cheatsheet, if any, is trying to represent an at-hand, concise, first bridge between theoretical foundations and applications developers approaching this world (not necessarily cryptography professionals). Of course this kind of resource cannot be a rigorous reference, but authoritative sources that I have consulted (just a few in this repo as well) are listed, to let the interested reader dig deeper.

A cheatsheet dealing with ZK basic core concepts

---

README.md

The ZK space is moving at a very fast-paced rate and new resources are constantly emerging, here I've added a few and fixed some markdown errors, are PRs welcome?

add(ZK whiteboard sessions, zkml), fix(markdown styling)

---

README.md

The latest snark tutorial using snarkjs and circom by Luozhu

Add a snark tutorial

---

README.md

Added Zero Knowledge Proof, MOOC Spring 2023 link

added Zero Knowledge Proof, MOOC Spring course

---

README.md

Old: https://discord.com/invite/8t4zXje
New: https://discordapp.com/invite/PhJY6Pm

Update README.md - Fix Zcash Community Chat Discord Link

---

README.md

Update to the correct link - the old link was broken/migrated.

Update the correct link

---

README.md

1. Add MIT's course
2. Update catalog

Add MIT's Course 

---

README.md

Vitalik's website has changed domain name, update it!
s/vitalik.ca/vitalik.eth.limo/g

Update vitalik's website url

---

README.md

Added 3 non-blockchain applications using zk

Add non-blockchain applications

---

README.md

Circom + halo2 0xParc learning group

added 0xPARC learning group

---

README.md

demo.matter-labs.io doesnt exist anymore

removed expired link
